### ISSUE TITLE
how can I generate mask image?

### ISSUE THREAD

**Issue by xiaomingjie** [fanhqme/DeepPointSet#10]
In the ImageCaptureGuide.pdf, the mask image should be prepared first. But I don't see the method to generate it. Could you or anyone help me?
Thanks a lot!

**Comment by AmyWan** [comment]
@xiaomingjie hi,would you like to share your solution about the question you asked.

**Comment by xiaomingjie** [comment]
@AmyWan Sorry. I still don't have a solution.

**Comment by sixftninja** [comment]
Did anyone find a solution to this?
